/* eslint-disable max-lines */
import type { ArchiveDocumentSeed } from "@earthquake-reports/shared";

export const esBaseData: ArchiveDocumentSeed[] = [
  {
    id: 71381,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "העתק אור עקיבא",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 49732,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מיפוי העתקים בברניקי",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 84050,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עדכון מעמד העתקים 2018",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 71043,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עדכון מעמד העתקים 2022",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 28924,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "פעילות טקטונית כרמל ונשר",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 85806,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "רכס חוסם צפוני בכרמל",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 84518,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "קריעת פני שטח בטבריה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 43221,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "העתק אחיהוד",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 54062,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מיקום העתק הכרמל מניתוח תתקרקע",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 20531,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מדידות רעש לאיתור העתק הכרמל",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 28385,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מפת סיכון ארצית להעתקה פעילה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 86975,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "העתקים פעילים אילת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 43725,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מבנה תלת מימדי למפרץ אילת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 51378,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "זמני חזרה של רעידות בכנרת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 28515,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "העתקים במדרון היבשת וטקטוניקת מלח",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 33624,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אפיון העתקים במדרון היבשת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 44497,
    category: "גיאולוגיה",
    subCategory: "הגברת חריגה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הגברת תנודות בעמק זבולון א",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 73230,
    category: "גיאולוגיה",
    subCategory: "הגברת חריגה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הגברת תנודות בשפלה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 38837,
    category: "גיאולוגיה",
    subCategory: "הגברת חריגה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הגברת תנודות בעמק זבולון ב",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 44504,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "היחס בין שטח וגודל גלישות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 47412,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "גלישות אזור אילת אילות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 63280,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "גלישות באזור בית שאן",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 93247,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סיכון נפילת סלעים חפציבה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 47576,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "טיפוסי כשל מדרון בחיפה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 71124,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מפת סכנה ארצית לגלישות צפון",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 60785,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מפת סכנה ארצית לגלישות דרום",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 18944,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "גלישות תת ימיות במדרון היבשת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 30862,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אלגוריתם לחיזוי גלישת קרקע",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 77482,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "התנזלות בבית שאן",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 32438,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "התנזלות בעמק זבולון",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 15452,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "התנזלות אילת אילות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 29079,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הערכה גיאוטכנית להתנזלות בזבולון",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 47840,
    category: "גיאולוגיה",
    subCategory: "עוצמת רעידה",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הערכת מיקום ועוצמה מלווינים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 34429,
    category: "גיאולוגיה",
    subCategory: "עוצמת רעידה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "שאלון עדכני לקביעת עוצמות סייסמיות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 30047,
    category: "גיאולוגיה",
    subCategory: "עוצמת רעידה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אימוץ סולם עוצמה אירופאי",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 87285,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "סימולציה לצונמי בים המלח",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 64444,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מודל סיכון לצונמי בת גלים ואילת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 57478,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הדמיית תרחישי צונמי",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 71996,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סף מגניטודה לצונמי",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 71977,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פגיעת צונמי בתשתיות ימיות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 17214,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "ניתוח היסטורי סכנה לצונמי",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 30476,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סיכום סיכונים בחיפה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 31251,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סיכונים והעתקים בבקעת הירדן",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 52391,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מיפוי סיכונים אזור מתלול צורים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 79389,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "בסיס נתונים גאודטי עבור הדרום",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 66857,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מיפוי סיכונים והעתקים בבית שאן",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 46514,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הסיכון לרעידת אדמה בטבריה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 13579,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תכנת ורוניק",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 68266,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "אפיון תופעות סביבה מרעידות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 44293,
    category: "ועדת ההיגוי",
    subCategory: "plans ותפיסות לאומיות",
    mediaType: "plans",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תפיסה לאומית לרעידת אדמה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 51490,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פוסטר הנחיות במשטרה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 14328,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פוסטר הנחיות בבתי חולים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 41626,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "russian",
    isPublish: false,
    status: "init",
    name: "עלון היערכות לרעידות אדמה רוסית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 49563,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "עלון היערכות לרעידות אדמה ערבית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 52536,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "english",
    isPublish: false,
    status: "init",
    name: "עלון היערכות לרעידות אדמה אנגלית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 45444,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עלון היערכות לרעידות אדמה עברית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 80743,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הנחיות ברעידת אדמה עברית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 71214,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "הנחיות ברעידת אדמה ערבית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 53736,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "russian",
    isPublish: false,
    status: "init",
    name: "הנחיות ברעידת אדמה רוסית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 29684,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הנחיות ברעידת אדמה אנגלית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 75622,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מצגת הסברה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 70638,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "כרזה בערבית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 92552,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "כרזה בעברית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 65565,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מדריך לתכנון מילוט במבני ציבור",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 79011,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "עלון צונמי ערבית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 86885,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "english",
    isPublish: false,
    status: "init",
    name: "עלון צונמי אנגלית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 57298,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עלון צונמי עברית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 97248,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "ועדה לבחינת הנחיות במוסדות חינוך",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 47010,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הנחיות לאנשים עם מוגבלות - מוסדות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 37556,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "guides",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "היערכות אנשים עם מוגבלות ערבית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 68111,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "היערכות אנשים עם מוגבלות עברית",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 22576,
    category: "היערכות הרשות המקומית",
    subCategory: "אתר סיוע לאוכלוסייה",
    mediaType: "plans",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אתר סיוע לאוכלוסיה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 15928,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "השוואת שיטות חישוב תגובת אתר",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 16416,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מדידות תגובת אתר אזור גלילות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 28546,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר אזור באר שבע",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 30456,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר באר שבע",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 26894,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר דימונה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 82139,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר שדה דב",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 51746,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר רחובות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 74519,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר קרית גת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 43031,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר קריות חיפה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 53266,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר צור יצחק",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 98228,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר עראבה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 59734,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר עמק זבולון",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 87664,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר נורדיה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 47158,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר מגדל העמק",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 74423,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר ירוחם",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 80980,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר ומיקרוזונציה אילת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 25990,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר גלילות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 61312,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר גדידה מכר",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 61669,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר בעיר טבריה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 18079,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר אשקלון",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 86901,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מדידות תגובת אתר אזור דימונה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 87745,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר אכסאל",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 71571,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אופן חישוב תגובת אתר",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 18351,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "איכון מקורות לרעידה בים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 51099,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פיזור מוקדים בגלבוע כרמל",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 64623,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הערת מקור רעד מגלי פי",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 83427,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "כיול הרשת להערכת רעידות רחוקות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 34157,
    category: "סיסמולוגיה",
    subCategory: "רעידות משנה",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "התפתחות בזמן של רעשי משנה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 67452,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מאגר אקסלוגרמות לתאוצות קרקע",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 69867,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מודל מהירות תלת מימדי לאיכון רעידות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 75317,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תאוצות קרקע בתקן הבניה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 42104,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "אלגוריתם להערכת תאוצות קרקע",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 16932,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חיזוק מבני אבן",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 44109,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מדריך לחיזוק מבנים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 25019,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "דוגמאות לחישוב לפי 413 חלק3",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 58538,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סקר רמות סיכון קביל",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 92454,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "גישות לשדרוג סייסמי",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 57250,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עמידות מבנים עם קירות הקשחה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 72333,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עמידות עמודים עטופים ביריעות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 71234,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אופטימיזציה של מבנים מבטון",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 77055,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חישוב תקופה בסיסית למבנים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 79621,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חציית העתק עי צנרת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 43456,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "שימוש בבידוד סייסמי במבנים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 56246,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תכנון מבנה על העתק פעיל",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 87790,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פרמטרים של רעידות ותכן מבנים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 84150,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חישוב זמן מחזור מבנים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 92276,
    category: "הנדסה סיסמית",
    subCategory: "אלמנטים לא מבניים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עיגון מערכות לא מבניות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 42255,
    category: "הנדסה סיסמית",
    subCategory: "הערכת נזק למבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "זיהוי והערכת נזק בבתי חולים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 37338,
    category: "הנדסה סיסמית",
    subCategory: "הערכת נזק למבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "יצירת תמונת מצב מבני חקלאות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 64080,
    category: "היערכות לצונאמי",
    subCategory: "מערך \"מים אדירים\"",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מודל תומך החלטה להתרעת צונמי",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 39868,
    category: "היערכות לצונאמי",
    subCategory: "תפיסה לאומית לצונמי",
    mediaType: "plans",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תפיסה לאומית לצונמי",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 22843,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכות התרעה מקומיות",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פרמטרים להתרעה להפסקת פעילות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 73218,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תפיסת הציבור את תרועה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 66336,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סקר היתכנות למערכת התרעה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 74535,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מדיניות התרעה לרעידות אדמה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 70208,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "reports",
    language: "english",
    isPublish: false,
    status: "init",
    name: "ועדה בינל להקמת מערכת התרעה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 73445,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "בחינה ראשונית למערכת התרעה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 87158,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אופטימיזציה של אלגוריתם התרעה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 74130,
    category: "היערכות אתרי מורשת",
    subCategory: "סיכונים באתרי מורשת",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "נספחים מדריך היערכות אתרי מורשת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 11343,
    category: "היערכות אתרי מורשת",
    subCategory: "סיכונים באתרי מורשת",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "נספחים תיק שטח אתרי מורשת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 21774,
    category: "היערכות אתרי מורשת",
    subCategory: "סיכונים באתרי מורשת",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מדריך היערכות אתרי מורשת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 78076,
    category: "שיקום ארוך טווח",
    subCategory: "שיקום ארוך טווח",
    mediaType: "plans",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "דוח שיקום ארוך טווח",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 10109,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות הציבור",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סגנון תקשורת סיכונים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 84234,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות הציבור",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סקר תפיסות האוכלוסיה על רעד",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 77601,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות הציבור",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הגדרת צורכי אוכלוסיות פגיעות אחרי רעידה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 88352,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מוכנות אוכלוסיית החרדים לרעידה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 12972,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מחקר בתי ספר ניסויים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 79084,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מחקר בתי ספר מערך",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 83491,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מחקר בתי ספר חוברת לתלמיד",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 37831,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מחקר בתי ספר השוואה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 20816,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "התנהגות אוכלוסיה עם מוגבלות",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 48441,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הנחיות בפישוט לשוני",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 90158,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הערכת נזק כלכלי באילת",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 41871,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הערכת נזקים מאקרו כלכליים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 38075,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חוסן תעשיית האירוח בישראל",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 76408,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "היערכות לרעד בעסקים קטנים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 41185,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים משפטיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "המערך הרגולטורי לרעידת אדמה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 36865,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות המדינה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חבילות מדיניות לחיזוק מבנים בפריפריה",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  },
  {
    id: 57314,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות המדינה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "גישות בהליך זיהוי אלמונים",
    type: "docs",
    summary: "",
    longSummary: "",
    publishDate: "",
    size: ""
  }
];